--
-- Script was generated by Devart dbForge Studio for SQL Server, Version 5.3.56.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 1/3/2018 4:09:40 PM
-- Server version: 13.00.4001
-- Client version: 
--



USE Tourine
GO

IF DB_NAME() <> N'Tourine' SET NOEXEC ON
GO

--
-- Create table "dbo.VersionInfo"
--
PRINT (N'Create table "dbo.VersionInfo"')
GO
CREATE TABLE dbo.VersionInfo (
  Version bigint NOT NULL,
  AppliedOn datetime NULL,
  Description nvarchar(1024) NULL
)
ON [PRIMARY]
GO

--
-- Create index "UC_Version" on table "dbo.VersionInfo"
--
PRINT (N'Create index "UC_Version" on table "dbo.VersionInfo"')
GO
CREATE UNIQUE CLUSTERED INDEX UC_Version
  ON dbo.VersionInfo (Version)
  ON [PRIMARY]
GO

--
-- Create table "dbo.Status"
--
PRINT (N'Create table "dbo.Status"')
GO
CREATE TABLE dbo.Status (
  ID int NOT NULL,
  Name nvarchar(50) NULL,
  CONSTRAINT PK_Status_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.Role"
--
PRINT (N'Create table "dbo.Role"')
GO
CREATE TABLE dbo.Role (
  ID int NOT NULL,
  Name varchar(50) NULL,
  CONSTRAINT PK_Role_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.[User]"
--
PRINT (N'Create table "dbo.[User]"')
GO
CREATE TABLE dbo.[User] (
  ID uniqueidentifier NOT NULL,
  Name nvarchar(50) NULL,
  RoleID int NULL,
  CONSTRAINT PK_User_ID PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT FK_User_Role_ID FOREIGN KEY (RoleID) REFERENCES dbo.Role (ID)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.Place"
--
PRINT (N'Create table "dbo.Place"')
GO
CREATE TABLE dbo.Place (
  Id uniqueidentifier NOT NULL,
  Name nvarchar(50) NULL,
  CONSTRAINT PK_Place_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.Hotel"
--
PRINT (N'Create table "dbo.Hotel"')
GO
CREATE TABLE dbo.Hotel (
  ID uniqueidentifier NOT NULL,
  Name nvarchar(50) NULL,
  CONSTRAINT PK_Hotel_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.Destination"
--
PRINT (N'Create table "dbo.Destination"')
GO
CREATE TABLE dbo.Destination (
  ID uniqueidentifier NOT NULL,
  Name nvarchar(50) NULL,
  CONSTRAINT PK_Destination_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.Customer"
--
PRINT (N'Create table "dbo.Customer"')
GO
CREATE TABLE dbo.Customer (
  Id uniqueidentifier NOT NULL,
  Name nvarchar(50) NULL,
  Family nvarchar(50) NULL,
  MobileNumber varchar(50) NULL,
  NationalCode nvarchar(50) NULL,
  BirthDate date NULL,
  PassportExpireDate date NULL,
  PassportNo varchar(50) NULL,
  CONSTRAINT PK_Customer_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.Currency"
--
PRINT (N'Create table "dbo.Currency"')
GO
CREATE TABLE dbo.Currency (
  ID int NOT NULL,
  Name nvarchar(50) NULL,
  Factor nvarchar(50) NULL,
  CONSTRAINT PK_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.PriceDetail"
--
PRINT (N'Create table "dbo.PriceDetail"')
GO
CREATE TABLE dbo.PriceDetail (
  ID uniqueidentifier NOT NULL,
  Price int NULL,
  CurrencyID int NULL,
  CONSTRAINT PK_PriceDetail_ID PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT FK_PriceDetail_Currency_ID FOREIGN KEY (CurrencyID) REFERENCES dbo.Currency (ID)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.Tour"
--
PRINT (N'Create table "dbo.Tour"')
GO
CREATE TABLE dbo.Tour (
  ID uniqueidentifier NOT NULL,
  Code nvarchar(50) NULL,
  DestinationID uniqueidentifier NULL,
  Capacity int NULL,
  StatusID int NULL,
  PriceDetailID uniqueidentifier NULL,
  Duration int NULL,
  Date datetime NULL,
  PlaceID uniqueidentifier NULL,
  isFlight bit NULL,
  AdultCount int NULL,
  AdultMinPrice int NULL,
  BusPrice int NULL,
  RoomPrice int NULL,
  FoodPrice int NULL,
  InfantPrice int NULL,
  CONSTRAINT PK_Tour_ID PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT FK_Tour_Destination_ID FOREIGN KEY (DestinationID) REFERENCES dbo.Destination (ID),
  CONSTRAINT FK_Tour_Place_Id FOREIGN KEY (PlaceID) REFERENCES dbo.Place (Id),
  CONSTRAINT FK_Tour_PriceDetail_ID FOREIGN KEY (PriceDetailID) REFERENCES dbo.PriceDetail (ID),
  CONSTRAINT FK_Tour_Status_ID FOREIGN KEY (StatusID) REFERENCES dbo.Status (ID)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.Block"
--
PRINT (N'Create table "dbo.Block"')
GO
CREATE TABLE dbo.Block (
  ID uniqueidentifier NOT NULL,
  Code nvarchar(50) NULL,
  TourID uniqueidentifier NULL,
  PresenterUID uniqueidentifier NULL,
  Price int NULL,
  Capacity int NULL,
  HotelID uniqueidentifier NULL,
  Parent uniqueidentifier NULL,
  CONSTRAINT PK_Coppon_ID PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT FK_Block_Hotel_ID FOREIGN KEY (HotelID) REFERENCES dbo.Hotel (ID),
  CONSTRAINT FK_Block_Tour_ID FOREIGN KEY (TourID) REFERENCES dbo.Tour (ID),
  CONSTRAINT FK_Block_User_ID FOREIGN KEY (PresenterUID) REFERENCES dbo.[User] (ID)
)
ON [PRIMARY]
GO

--
-- Create foreign key "FK_Block_Block_ID" on table "dbo.Block"
--
PRINT (N'Create foreign key "FK_Block_Block_ID" on table "dbo.Block"')
GO
ALTER TABLE dbo.Block WITH CHECK
  ADD CONSTRAINT FK_Block_Block_ID FOREIGN KEY (Parent) REFERENCES dbo.Block (ID)
GO
SET NOEXEC OFF
GO