--
-- Script was generated by Devart dbForge Studio for SQL Server, Version 5.3.56.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 1/14/2018 4:34:29 PM
-- Server version: 13.00.4001
-- Client version: 
--



USE Tourine
GO

IF DB_NAME() <> N'Tourine' SET NOEXEC ON
GO

--
-- Create table "dbo.Place"
--
PRINT (N'Create table "dbo.Place"')
GO
CREATE TABLE dbo.Place (
  Id uniqueidentifier NOT NULL CONSTRAINT DF_Place_Id DEFAULT (newid()) ROWGUIDCOL,
  Name nvarchar(50) NULL,
  CONSTRAINT PK_Place_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.Destination"
--
PRINT (N'Create table "dbo.Destination"')
GO
CREATE TABLE dbo.Destination (
  ID uniqueidentifier NOT NULL DEFAULT (newid()),
  Name nvarchar(50) NULL,
  CONSTRAINT PK_Destination_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.Tour"
--
PRINT (N'Create table "dbo.Tour"')
GO
CREATE TABLE dbo.Tour (
  ID uniqueidentifier NOT NULL CONSTRAINT DF_Tour_ID DEFAULT (newid()) ROWGUIDCOL,
  Code nvarchar(50) NULL,
  DestinationID uniqueidentifier NULL,
  Capacity AS ([AdultCount]+[InfantCount]),
  Status tinyint NULL,
  Duration int NULL,
  StartDate datetime NULL,
  PlaceID uniqueidentifier NULL,
  isFlight bit NULL,
  AdultCount int NULL,
  AdultMinPrice int NULL,
  BusPrice int NULL,
  RoomPrice int NULL,
  FoodPrice int NULL,
  InfantPrice int NULL,
  InfantCount int NULL,
  CreationDate datetime NULL,
  CONSTRAINT PK_Tour_ID PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT FK_Tour_Destination_ID FOREIGN KEY (DestinationID) REFERENCES dbo.Destination (ID),
  CONSTRAINT FK_Tour_Place_Id FOREIGN KEY (PlaceID) REFERENCES dbo.Place (Id)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.Customer"
--
PRINT (N'Create table "dbo.Customer"')
GO
CREATE TABLE dbo.Customer (
  Id uniqueidentifier NOT NULL CONSTRAINT DF_Customer_Id DEFAULT (newid()) ROWGUIDCOL,
  Name nvarchar(50) NULL,
  Family nvarchar(50) NULL,
  MobileNumber varchar(15) NULL,
  Phone varchar(15) NULL,
  CONSTRAINT PK_Reagent_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.[User]"
--
PRINT (N'Create table "dbo.[User]"')
GO
CREATE TABLE dbo.[User] (
  Id uniqueidentifier NOT NULL CONSTRAINT DF_User_Id DEFAULT (newid()) ROWGUIDCOL,
  Username nvarchar(50) NULL,
  Password nvarchar(50) NULL,
  CustomerId uniqueidentifier NULL,
  Role tinyint NULL,
  CONSTRAINT PK_User_ID PRIMARY KEY CLUSTERED (Id),
  CONSTRAINT FK_User_Customer FOREIGN KEY (CustomerId) REFERENCES dbo.Customer (Id) ON DELETE CASCADE ON UPDATE CASCADE
)
ON [PRIMARY]
GO

--
-- Create table "dbo.Block"
--
PRINT (N'Create table "dbo.Block"')
GO
CREATE TABLE dbo.Block (
  ID uniqueidentifier NOT NULL CONSTRAINT DF_Block_ID DEFAULT (newid()) ROWGUIDCOL,
  Code nvarchar(50) NULL,
  TourID uniqueidentifier NULL,
  Price int NULL,
  Capacity int NULL,
  ParentId uniqueidentifier NULL,
  CustomerId uniqueidentifier NULL,
  SubmitDate datetime NULL,
  CONSTRAINT PK_Coppon_ID PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT FK_Block_Customer FOREIGN KEY (CustomerId) REFERENCES dbo.Customer (Id),
  CONSTRAINT FK_Block_Tour_ID FOREIGN KEY (TourID) REFERENCES dbo.Tour (ID)
)
ON [PRIMARY]
GO

--
-- Create foreign key "FK_Block_Block_ID" on table "dbo.Block"
--
PRINT (N'Create foreign key "FK_Block_Block_ID" on table "dbo.Block"')
GO
ALTER TABLE dbo.Block WITH CHECK
  ADD CONSTRAINT FK_Block_Block_ID FOREIGN KEY (ParentId) REFERENCES dbo.Block (ID)
GO

--
-- Create table "dbo.Currency"
--
PRINT (N'Create table "dbo.Currency"')
GO
CREATE TABLE dbo.Currency (
  ID int NOT NULL,
  Name nvarchar(50) NULL,
  Factor int NULL,
  CONSTRAINT PK_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.PriceDetail"
--
PRINT (N'Create table "dbo.PriceDetail"')
GO
CREATE TABLE dbo.PriceDetail (
  ID uniqueidentifier NOT NULL CONSTRAINT DF_PriceDetail_ID DEFAULT (newid()) ROWGUIDCOL,
  value money NULL,
  CurrencyID int NULL,
  TourId uniqueidentifier NULL,
  CONSTRAINT PK_PriceDetail_ID PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT FK_PriceDetail_Currency_ID FOREIGN KEY (CurrencyID) REFERENCES dbo.Currency (ID),
  CONSTRAINT FK_PriceDetail_Tour FOREIGN KEY (TourId) REFERENCES dbo.Tour (ID)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.Agency"
--
PRINT (N'Create table "dbo.Agency"')
GO
CREATE TABLE dbo.Agency (
  Id uniqueidentifier NOT NULL CONSTRAINT DF_Agency_Id DEFAULT (newid()) ROWGUIDCOL,
  Name nvarchar(50) NULL,
  PhoneNumber varchar(11) NULL,
  CONSTRAINT PK_Agency PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.Passenger"
--
PRINT (N'Create table "dbo.Passenger"')
GO
CREATE TABLE dbo.Passenger (
  Id uniqueidentifier NOT NULL CONSTRAINT DF_Passenger_Id DEFAULT (newid()) ROWGUIDCOL,
  Name nvarchar(50) NULL,
  Family nvarchar(50) NULL,
  MobileNumber varchar(11) NULL,
  NationalCode varchar(10) NULL,
  BirthDate date NOT NULL,
  PassportExpireDate date NOT NULL,
  AgencyId uniqueidentifier NULL,
  PassportNo varchar(50) NULL,
  CONSTRAINT PK_Customer_Id PRIMARY KEY CLUSTERED (Id),
  CONSTRAINT FK_Passenger_Agency_Id FOREIGN KEY (AgencyId) REFERENCES dbo.Agency (Id)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.PassengerList"
--
PRINT (N'Create table "dbo.PassengerList"')
GO
CREATE TABLE dbo.PassengerList (
  Id uniqueidentifier NOT NULL CONSTRAINT DF_PassengerList_Id DEFAULT (newid()) ROWGUIDCOL,
  BlockId uniqueidentifier NULL,
  PassengerId uniqueidentifier NULL,
  CONSTRAINT PK_PassengerList PRIMARY KEY CLUSTERED (Id),
  CONSTRAINT FK_PassengerList_Block FOREIGN KEY (BlockId) REFERENCES dbo.Block (ID),
  CONSTRAINT FK_PassengerList_Passenger FOREIGN KEY (PassengerId) REFERENCES dbo.Passenger (Id)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.AgencyCustomer"
--
PRINT (N'Create table "dbo.AgencyCustomer"')
GO
CREATE TABLE dbo.AgencyCustomer (
  Id uniqueidentifier NOT NULL CONSTRAINT DF_AgencyCustomer_Id DEFAULT (newid()) ROWGUIDCOL,
  AgencyId uniqueidentifier NOT NULL,
  CustomerId uniqueidentifier NOT NULL,
  CONSTRAINT PK_AgencyCustomer PRIMARY KEY CLUSTERED (Id),
  CONSTRAINT FK_AgencyCustomer_Agency FOREIGN KEY (AgencyId) REFERENCES dbo.Agency (Id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_AgencyCustomer_Customer FOREIGN KEY (CustomerId) REFERENCES dbo.Customer (Id) ON DELETE CASCADE ON UPDATE CASCADE
)
ON [PRIMARY]
GO
SET NOEXEC OFF
GO