-- 
-- Script was generated by Devart dbForge Studio for SQL Server, Version 5.3.56.0
-- Product Home Page: http://www.devart.com/dbforge/sql/studio
-- Script date 1/13/2018 9:15:20 PM
-- Server version: 13.00.4001
-- Run this script against Tourine to synchronize it with Tourine_new
-- Please backup your target database before running this script
-- 
SET CONCAT_NULL_YIELDS_NULL, ANSI_NULLS, ANSI_PADDING, QUOTED_IDENTIFIER, ANSI_WARNINGS, ARITHABORT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

USE [Tourine]
GO

IF DB_NAME() <> N'Tourine' SET NOEXEC ON
GO


--
-- Rename column "[Phone]" to "[PhoneNo]" on table "dbo.Customer"
--
EXEC sp_rename N'[dbo].[Customer].[Phone]', N'PhoneNo', 'COLUMN'
GO

--
-- Rename column "[MobileNumber]" to "[MobileNo]" on table "dbo.Customer"
--
EXEC sp_rename N'[dbo].[Customer].[MobileNumber]', N'MobileNo', 'COLUMN'
GO

--
-- Create column "[Address]" on table "[dbo].[Customer]"
--
ALTER TABLE [dbo].[Customer]
  ADD [Address] [nvarchar](150) NULL
GO

--
-- Set NOEXEC to off
--
SET NOEXEC OFF
GO