--
-- Script was generated by Devart dbForge Studio for SQL Server, Version 5.3.56.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 09/11/1396 06:15:41 ق.ظ
-- Server version: 13.00.4001
-- Client version: 
--



USE Tourine
GO

IF DB_NAME() <> N'Tourine' SET NOEXEC ON
GO

SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--
-- Create procedure "dbo.UpdateTourSatus"
--
GO
PRINT (N'Create procedure "dbo.UpdateTourSatus"')
GO
CREATE PROCEDURE dbo.UpdateTourSatus
AS 
UPDATE Tour
SET Status = 2
WHERE StartDate < GETDATE() AND Status = 1
GO
SET NOEXEC OFF
GO