--
-- Script was generated by Devart dbForge Studio for SQL Server, Version 5.3.56.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 11/11/1396 04:00:00 ب.ظ
-- Server version: 13.00.4001
-- Client version: 
--



USE Tourine
GO

IF DB_NAME() <> N'Tourine' SET NOEXEC ON
GO

--
-- Create table "dbo.Place"
--
PRINT (N'Create table "dbo.Place"')
GO
CREATE TABLE dbo.Place (
  Id uniqueidentifier NOT NULL CONSTRAINT DF_Place_Id DEFAULT (newid()) ROWGUIDCOL,
  Name nvarchar(50) NOT NULL,
  CONSTRAINT PK_Place_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.Passenger"
--
PRINT (N'Create table "dbo.Passenger"')
GO
CREATE TABLE dbo.Passenger (
  Id uniqueidentifier NOT NULL CONSTRAINT DF_Passenger_Id DEFAULT (newid()) ROWGUIDCOL,
  Name nvarchar(50) NOT NULL,
  Family nvarchar(50) NOT NULL,
  MobileNumber varchar(11) NULL,
  NationalCode varchar(10) NOT NULL,
  BirthDate date NOT NULL,
  PassportExpireDate date NULL,
  PassportNo varchar(50) NULL,
  CONSTRAINT PK_Customer_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.Destination"
--
PRINT (N'Create table "dbo.Destination"')
GO
CREATE TABLE dbo.Destination (
  ID uniqueidentifier NOT NULL DEFAULT (newid()),
  Name nvarchar(50) NOT NULL,
  CONSTRAINT PK_Destination_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.TourDetail"
--
PRINT (N'Create table "dbo.TourDetail"')
GO
CREATE TABLE dbo.TourDetail (
  ID uniqueidentifier NOT NULL CONSTRAINT DF_Block_ID DEFAULT (newid()) ROWGUIDCOL,
  DestinationId uniqueidentifier NOT NULL,
  Duration int NULL,
  StartDate datetime NULL,
  PlaceId uniqueidentifier NOT NULL,
  IsFlight bit NULL,
  InfantPrice bigint NULL,
  BusPrice bigint NULL,
  RoomPrice bigint NULL,
  FoodPrice bigint NULL,
  SubmitDate datetime NOT NULL,
  CONSTRAINT PK_Coppon_ID PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT FK_TourDetail_Destination_ID FOREIGN KEY (DestinationId) REFERENCES dbo.Destination (ID),
  CONSTRAINT FK_TourDetail_Place_Id FOREIGN KEY (PlaceId) REFERENCES dbo.Place (Id)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.Customer"
--
PRINT (N'Create table "dbo.Customer"')
GO
CREATE TABLE dbo.Customer (
  Id uniqueidentifier NOT NULL CONSTRAINT DF_Customer_Id DEFAULT (newid()) ROWGUIDCOL,
  Name nvarchar(50) NOT NULL,
  Family nvarchar(50) NOT NULL,
  MobileNumber varchar(15) NULL,
  Phone varchar(15) NULL,
  CONSTRAINT PK_Reagent_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.[User]"
--
PRINT (N'Create table "dbo.[User]"')
GO
CREATE TABLE dbo.[User] (
  Id uniqueidentifier NOT NULL CONSTRAINT DF_User_Id DEFAULT (newid()) ROWGUIDCOL,
  Username nvarchar(50) NOT NULL,
  Password nvarchar(50) NOT NULL,
  CustomerId uniqueidentifier NOT NULL,
  Role tinyint NOT NULL,
  CONSTRAINT PK_User_ID PRIMARY KEY CLUSTERED (Id),
  CONSTRAINT FK_User_Customer_Id FOREIGN KEY (CustomerId) REFERENCES dbo.Customer (Id)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.Currency"
--
PRINT (N'Create table "dbo.Currency"')
GO
CREATE TABLE dbo.Currency (
  ID int NOT NULL,
  Name nvarchar(50) NOT NULL,
  Factor float NULL,
  CONSTRAINT PK_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.Agency"
--
PRINT (N'Create table "dbo.Agency"')
GO
CREATE TABLE dbo.Agency (
  Id uniqueidentifier NOT NULL CONSTRAINT DF_Agency_Id DEFAULT (newid()) ROWGUIDCOL,
  Name nvarchar(50) NOT NULL,
  PhoneNumber varchar(11) NULL,
  CONSTRAINT PK_Agency PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.Tour"
--
PRINT (N'Create table "dbo.Tour"')
GO
CREATE TABLE dbo.Tour (
  ID uniqueidentifier NOT NULL CONSTRAINT DF_Tour_ID DEFAULT (newid()) ROWGUIDCOL,
  Capacity int NULL,
  BasePrice bigint NULL,
  ParentId uniqueidentifier NULL,
  Code nvarchar(50) NULL,
  Status tinyint NOT NULL,
  TourDetailId uniqueidentifier NULL,
  AgencyId uniqueidentifier NULL,
  CreationDate datetime NOT NULL,
  CONSTRAINT PK_Tour_ID PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT FK_Tour_Agency_Id FOREIGN KEY (AgencyId) REFERENCES dbo.Agency (Id),
  CONSTRAINT FK_Tour_TourDetail_ID FOREIGN KEY (TourDetailId) REFERENCES dbo.TourDetail (ID)
)
ON [PRIMARY]
GO

--
-- Create foreign key "FK_Tour_Tour_ID" on table "dbo.Tour"
--
PRINT (N'Create foreign key "FK_Tour_Tour_ID" on table "dbo.Tour"')
GO
ALTER TABLE dbo.Tour WITH CHECK
  ADD CONSTRAINT FK_Tour_Tour_ID FOREIGN KEY (ParentId) REFERENCES dbo.Tour (ID)
GO

--
-- Create table "dbo.Team"
--
PRINT (N'Create table "dbo.Team"')
GO
CREATE TABLE dbo.Team (
  Id uniqueidentifier NOT NULL DEFAULT (newid()),
  TourId uniqueidentifier NOT NULL,
  Price bigint NULL,
  Buyer uniqueidentifier NOT NULL,
  Count int NULL,
  SubmitDate datetime NOT NULL,
  CONSTRAINT PK_Team_Id PRIMARY KEY CLUSTERED (Id),
  CONSTRAINT FK_Team_Passenger_Id FOREIGN KEY (Buyer) REFERENCES dbo.Passenger (Id),
  CONSTRAINT FK_Team_Tour_ID FOREIGN KEY (TourId) REFERENCES dbo.Tour (ID)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.TeamPassenger"
--
PRINT (N'Create table "dbo.TeamPassenger"')
GO
CREATE TABLE dbo.TeamPassenger (
  Id uniqueidentifier NOT NULL DEFAULT (newid()),
  TeamId uniqueidentifier NOT NULL,
  PassengerId uniqueidentifier NOT NULL,
  CONSTRAINT PK_TeamPassenger_Id PRIMARY KEY CLUSTERED (Id),
  CONSTRAINT FK_TeamPassenger_Passenger_Id FOREIGN KEY (PassengerId) REFERENCES dbo.Passenger (Id),
  CONSTRAINT FK_TeamPassenger_Team_Id FOREIGN KEY (TeamId) REFERENCES dbo.Team (Id)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.Service"
--
PRINT (N'Create table "dbo.Service"')
GO
CREATE TABLE dbo.Service (
  Id uniqueidentifier NOT NULL DEFAULT (newid()),
  PassengerId uniqueidentifier NOT NULL,
  TourId uniqueidentifier NOT NULL,
  Type tinyint NOT NULL,
  Status tinyint NOT NULL,
  CONSTRAINT PK_Service_Id PRIMARY KEY CLUSTERED (Id),
  CONSTRAINT FK_Service_Passenger_Id FOREIGN KEY (PassengerId) REFERENCES dbo.Passenger (Id),
  CONSTRAINT FK_Service_Tour_ID FOREIGN KEY (TourId) REFERENCES dbo.Tour (ID)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.PriceDetail"
--
PRINT (N'Create table "dbo.PriceDetail"')
GO
CREATE TABLE dbo.PriceDetail (
  ID uniqueidentifier NOT NULL CONSTRAINT DF_PriceDetail_ID DEFAULT (newid()) ROWGUIDCOL,
  value bigint NOT NULL,
  CurrencyID int NOT NULL,
  TourId uniqueidentifier NOT NULL,
  Title nvarchar(100) NULL,
  CONSTRAINT PK_PriceDetail_ID PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT FK_PriceDetail_Currency_ID FOREIGN KEY (CurrencyID) REFERENCES dbo.Currency (ID),
  CONSTRAINT FK_PriceDetail_Tour_ID FOREIGN KEY (TourId) REFERENCES dbo.Tour (ID)
)
ON [PRIMARY]
GO

--
-- Create table "dbo.AgencyCustomer"
--
PRINT (N'Create table "dbo.AgencyCustomer"')
GO
CREATE TABLE dbo.AgencyCustomer (
  Id uniqueidentifier NOT NULL CONSTRAINT DF_AgencyCustomer_Id DEFAULT (newid()) ROWGUIDCOL,
  AgencyId uniqueidentifier NOT NULL,
  CustomerId uniqueidentifier NOT NULL,
  CONSTRAINT PK_AgencyCustomer PRIMARY KEY CLUSTERED (Id),
  CONSTRAINT FK_AgencyCustomer_Agency_Id FOREIGN KEY (AgencyId) REFERENCES dbo.Agency (Id),
  CONSTRAINT FK_AgencyCustomer_Customer_Id FOREIGN KEY (CustomerId) REFERENCES dbo.Customer (Id)
)
ON [PRIMARY]
GO
SET NOEXEC OFF
GO